- API Design:
    - api_design/index.md

    - Fundamentals:
        - api_design/fundamentals/overview.md
        - api_design/fundamentals/1_level/1_level_fundamentals.md
        - api_design/fundamentals/2_level/2_level_fundamentals.md
        - api_design/fundamentals/summary.md

    - API Styles:
        - api_design/api_styles/overview.md

        - REST:
            - api_design/api_styles/rest/overview.md
            - api_design/api_styles/rest/1_level/1_level_rest.md
            - api_design/api_styles/rest/2_level/2_level_rest.md
            - api_design/api_styles/rest/3_level/3_level_rest.md
            - api_design/api_styles/rest/summary.md

        - api_design/api_styles/summary.md

    - Authentication:
        - api_design/authentication/overview.md

        - Fundamentals:
            - api_design/authentication/fundamentals/overview.md
            - api_design/authentication/fundamentals/1_level/1_level_fundamentals.md
            - api_design/authentication/fundamentals/summary.md

        - Authentication Methods:
            - api_design/authentication/methods/overview.md

            - Session-Based Authentication:
                - api_design/authentication/methods/session_based/overview.md
                - api_design/authentication/methods/session_based/session_based.md
                - api_design/authentication/methods/session_based/summary.md

            - Token-Based Authentication:
                - api_design/authentication/methods/token_based/overview.md
                - api_design/authentication/methods/token_based/token_based.md
                - api_design/authentication/methods/token_based/summary.md

            - api_design/authentication/methods/summary.md

        - api_design/authentication/summary.md

    - Authorization:
        - api_design/authorization/overview.md
        - api_design/authorization/1_level/1_level_authorization.md
        - api_design/authorization/2_level/2_level_authorization.md
        - api_design/authorization/summary.md